// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stchvygpxhwqzlnlppka.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0Y2h2eWdweGh3cXpsbmxwcGthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzMjUwNjYsImV4cCI6MjA1MTkwMTA2Nn0.FvH4wOoCVz3XqfKOQXmRbGDkz2-_1HgS2okPyC8nMmw";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);